### PR TITLE
Topic/add cred scan to build

### PR DESCRIPTION
**Pull request by SebastianSchuetze**
# PR Summary

Including Credscan from the Microsoft Security Code Analysis from Microsoft, which enables to check for credentials in source code, thus improving code quality.

Related to: #185 

## PR Checklist

since this is only improving the pipeline, the checklist would not apply.

### CODE REVIEW

**Comment by DarqueWarrior** [comment]
I will review ASAP

**Comment by DarqueWarrior** [comment]
I think I found the people to Email. But if you know for sure who to contact let me know so I can get the extension added to the org.

**Comment by SebastianSchuetze** [comment]
@DarqueWarrior I added also a documentation page to the new CredScan task if people need to add suppression rules for unit tests. 
Please tell me if I put it in the correct folder (I created the folder "build").

Also, I do not fully understand the suppression rules for "hash" type suppressions. If you want to use file-based suppression then we should think of a constants file for passwords that can be used within unit tests. Otherwise, we need to add many files to the suppression rules in the future.

What would be your suggestion?

And thanks for the quick installation of the task! 😄

**Comment by DarqueWarrior** [comment]
I like the idea of a constants file with fake creds to use in tests.

**Pull request merged**
