### PR TITLE
Improve dynamic parameters

### PR DESCRIPTION
**Pull request by MichelZ**
# PR Summary

Building dynamic parameters seems to be fragmented and not well thought through.
I've replaced it with an open source version with proper attribution that allows to add one or more dynamic parameters easily. They can be appended and the existing helper functions have been adapted to use this code. 

All test complete properly :)

## PR Checklist

- [ ] [Write Help](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#write-help)
- [ ] [Write Unit Test](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#write-unit-test)
- [ ] [Update CHANGELOG.md](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#add-a-format-file)

(no need IMHO, current tests work)

### CODE REVIEW

**Comment by MichelZ** [comment]
Also fixed a bug in `_buildProcessNameDynamicParam `

 ```
# Generate and set the ValidateSet
   if ($([VSTeamProcessCache]::timestamp) -ne (Get-Date).Minute) {
      $arrSet = _getProcesses
      [VSTeamProcessCache]::processes = $arrSet
      [VSTeamProcessCache]::timestamp = (Get-Date).Minute
   }
   else {
      $arrSet = [VSTeamProcessCache]::projects
   }
```

Notice in the `else`clause, it retrieves the `projects` property instead of the `process` property.

**Comment by MichelZ** [comment]
I'd forfait this in favor of #275

**Comment by SebastianSchuetze** [comment]
so you wanna close this or wait until the other one is clarified?

**Comment by MichelZ** [comment]
@SebastianSchuetze Wait until the other one is clarified. If it's accepted - let's close this one. If it's rejected - I'd like to get it in :)

**Comment by DarqueWarrior** [comment]
Are we all in agreement that we prefer the class based solution to this concern? If so I will close this PR.

**Comment by MichelZ** [comment]
Absolutely

**Comment by SebastianSchuetze** [comment]
Closing this PR since @MichelZ also agrees. But thanks for your effort! It is actually luxury for OO maintainer when several solutions compete to the same problem. ;-)

**Pull request closed without merging**
