### PR TITLE
Add Description for Azure RMService Connection

### PR DESCRIPTION
**Pull request by arturopolanco**
# PR Summary

Description field is added to the "Add-VSTeamAzureRMServiceEndpoint" cmdlet.  As it is already part of the AzDo API is enough to add it to the JSON object and parse it to "Add-VSTeamServiceEndpoint" 

## PR Checklist

- [x] [Write Help](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#write-help)
- [x] [Write Unit Test](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#write-unit-test)
- [x] [Update CHANGELOG.md](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#update-changelogmd)

### CODE REVIEW

**Comment by SebastianSchuetze** [comment]
@arturopolanco somehow the reference is not found when running unit tests on Ubuntu.

**Comment by SebastianSchuetze** [comment]
Also please update the version in the psd1 file.

**Comment by arturopolanco** [comment]
> @arturopolanco somehow the reference is not found when running unit tests on Ubuntu.

Hey Sebastian, there was a wrong reference, I should work now.  let me know how it goes

**Review by SebastianSchuetze — APPROVED** [review]
all fine. I can merge!

**Pull request merged**
