### PR TITLE
Add Process Template Support

### PR DESCRIPTION
**Pull request by fifthstreetpartners**
# PR Summary

## PR Checklist

- [x] [Write Help](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#write-help)
- [x] [Write Unit Test](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#write-unit-test)
- [x] [Update VSTeam.psd1](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#add-a-format-file)
- [x] [Update CHANGELOG.md](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#add-a-format-file)

### CODE REVIEW

**Comment by DarqueWarrior** [comment]
The alias Get-Process is going to cause problems.  I would suggest you just don't add it. Get-Process is an out of the box PowerShell cmdlet. It is very popular and we don't want to take that one over.

**Comment by DarqueWarrior** [comment]
My only other feedback is what should be the default format of the results to Get-VSTeamProcess? Currently it is a list and it shows the ID and URL. I am not sure why anyone would need to see that by default. I might suggest adding a table format that only shows the name and description. Users could always run Get-VSTeamProcess | FL * to get the current list view.

This is really nice work.

**Comment by fifthstreetpartners** [comment]
> 
> 
> The alias Get-Process is going to cause problems. I would suggest you just don't add it. Get-Process is an out of the box PowerShell cmdlet. It is very popular and we don't want to take that one over.

I thought about that actually but figured I'd include it just in case.  No problem taking it out.

**Comment by fifthstreetpartners** [comment]
> 
> 
> My only other feedback is what should be the default format of the results to Get-VSTeamProcess? Currently it is a list and it shows the ID and URL. I am not sure why anyone would need to see that by default. I might suggest adding a table format that only shows the name and description. Users could always run Get-VSTeamProcess | FL * to get the current list view.
> 
> This is really nice work.

No problem, I'll add that.

**Comment by fifthstreetpartners** [comment]
Ready for review

**Comment by DarqueWarrior** [comment]
Make sure you import the module and run Invoke-Pester from the Unit\Test folder. I see two tests failing.

**Comment by DarqueWarrior** [comment]
The tests were just missing a mock. I put them in there. Don't worry about it.

**Comment by fifthstreetpartners** [comment]
Sorry I missed that test.  Anything else you want me to change?

**Comment by DarqueWarrior** [comment]
Merging into master now. Thanks so much for your support.

**Pull request merged**
