### PR TITLE
Add option to Merge or Overwrite Bits in Add-VSTeamAccessControlEntry

### PR DESCRIPTION
**Pull request by mrwalters1988**
# PR Summary

This enables the option mentioned in the inline comments of Add-VSTeamAccessControlEntry to choose whether to merge the Bits or to Overwrite the bits. 

## PR Checklist

- [x] [Write Help](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#write-help)
- [x] [Write Unit Test](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#write-unit-test)
- [x] [Update CHANGELOG.md](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#update-changelogmd)

### CODE REVIEW

**Comment by mrwalters1988** [comment]
I didn't see any changes that needed to be made in the tests, and changelog looks like it's only updated when several PRs are approved and merged in, so I did not update that either. Can do so if needed.

**Comment by mrwalters1988** [comment]
Any update on this?

**Review by SebastianSchuetze — CHANGES_REQUESTED** [review]
A new unit test is needed that tests your switch parameter. You need to test that the sent body includes the value set when overwriting. When you added the test and all is green. I will merge it. :-)

**Review by SebastianSchuetze — APPROVED** [review]

**Comment by mrwalters1988** [comment]
Thanks @SebastianSchuetze I had set aside time next week to add the unit test, but I appreciate you adding it for me. Happy to have contributed.

**Pull request merged**
