### PR TITLE
fix #531 when Version is not set in Set-VSTeamAccount

### LINKED ISSUE #531: Set-VSTeamAccount Error on Module Import
### Steps to reproduce

```powershell
Import-Module -Name VSTeam
```
I'm getting this error while importing the module on version `7.13.0`. Normally, I wouldn't even use the `-Version` parameter when using `Set-VSTeamAccount` cmdlet.

### Expected behavior

The module would import without errors.

### Actual behavior?

I see the following error displayed:

```text
Set-VSTeamAccount: Cannot validate argument on parameter 'Version'. The argument "" does not belong to the set "TFS2017,TFS2018,AzD2019,VSTS,AzD,TFS2017U1,TFS2017U2,TFS2017U3,TFS2018U1,TFS2018U2,TFS2018U3,AzD2019U1" specified by the ValidateSet attribute. Supply an argument that is in the set and then try the command again.
```

### On Which OS have you tried it?

Windows

### What was your server version?

Azure DevOps Services

### Other server version

_No response_

### Log output of used API

```shell
Billing                     :
Build                       : 3.0
Core                        : 3.0
DistributedTask             : 3.0-preview
DistributedTaskReleased     :
ExtensionsManagement        : 3.0-preview
Git                         : 3.0
Graph                       :
HierarchyQuery              :
MemberEntitlementManagement :
Packaging                   : 3.0-preview
Pipelines                   :
Policy                      : 3.0
Processes                   :
Release                     : 3.0-preview
ServiceEndpoints            : 3.0-preview
TaskGroups                  : 3.0-preview
Tfvc                        : 3.0
VariableGroups              :
Version                     : TFS2017
Wiki                        :
WorkItemTracking            : 3.0
```

### Log output of $PSVersionTable

```shell
Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### PR DESCRIPTION
**Pull request by mnieto**
# PR Summary

fix #531 when Version is not set in Set-VSTeamAccount

## PR Checklist

- [x] [Write Help](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#write-help)
- [x] [Write Unit Test](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#write-unit-test)
- [x] [Update CHANGELOG.md](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#update-changelogmd)

### CODE REVIEW

**Comment by SebastianSchuetze** [comment]
Can you explain what happens if the vsteam module is already set and it's still overwritten.

I am thinking to start to write unit tests for the psm1 with Pester. This seems to get more complicated. So I think we should test the import part as well.

**Comment by SebastianSchuetze** [comment]
Ah I see the issue

**Comment by mnieto** [comment]
> I am thinking to start to write unit tests for the psm1 with Pester. This seems to get more complicated. So I think we should test the import part as well.

Yes, I agree
I don't have experience enough with Pester.  .psm1 files are complex to test. Perhaps we can move most of the functionality to an internal testable function and keep the psm1 file as much simple as possible

**Comment by SebastianSchuetze** [comment]
There is a recommendation:

https://pester.dev/docs/usage/modules

Testing the functions would be fine but also testing the import on different OS itself would also be important. I have done this at work but I got it from an example on github. I need to check.

**Comment by SebastianSchuetze** [comment]
Found it: https://powershellexplained.com/2017-01-21-powershell-module-continious-delivery-pipeline/#psm1-module

**Pull request merged**
