### PR TITLE
Added exclusion / and batching for yaml pipeline

### PR DESCRIPTION
**Pull request by SebastianSchuetze**
This is to optimize the pipeline to not trigger on files that do not need a build.

The following things are excluded:

- README.md
- CODE_OF_CONDUCT.md
- CHANGELOG.md
- .gitignore
- .editorconfig
- LICENSE
- dist/*
- docs/*
- .vscode/*
- .github/*

also configured the PRs are cancelled as soon as a new commit has been done as well as that changes are batched when committed on a master branch instead of triggering new build for each commit.

### CODE REVIEW

**Comment by SebastianSchuetze** [comment]
I will then try simple white space changes to the files to see if they trigger the pipeline.

**Comment by SebastianSchuetze** [comment]
it is very strange. My current setup looks as follow:

```yaml
trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include: 
      - '*'
    exclude:
    - README.md
    - CODE_OF_CONDUCT.md
    - CHANGELOG.md
    - .gitignore
    - .editorconfig
    - LICENSE
    - dist/*
    - docs/*
    - .vscode/*
    - .github/*
pr:
  autoCancel: true
  branches:
    include:
    - master
  paths:
    include: 
    - '*'
    exclude:
    - README.md
    - CODE_OF_CONDUCT.md
    - CHANGELOG.md
    - .gitignore
    - .editorconfig
    - LICENSE
    - dist/*
    - docs/*
    - .vscode/*
    - .github/*
```

It kind of evolved and I added a configuration as you can see and the tried to trigger it. According to the example here a simple `- README.md` in the exclude path config should help. But it still triggers...

https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=example%2Cparameter-schema#pr-trigger

@DarqueWarrior any idea? did you define triggers seperately on Azure DevOps site on pipeline level?

**Comment by DarqueWarrior** [comment]
I had a trigger override set. I removed it. Lets see if that fixes this for you.

**Comment by SebastianSchuetze** [comment]
Cool. I gonna check later.

**Comment by SebastianSchuetze** [comment]
@DarqueWarrior I have tried a lot and it does not seem to work as the documentation states.
I try to exclude single files from the trigger, but they are still being triggered. I created a bug report:

https://developercommunity.visualstudio.com/content/problem/1014853/github-pr-trigger-exclude-path-not-working-for-fil.html

Maybe you have the possibility to find out if this is actually by design?

**Comment by oising** [comment]
Same issue for me. I've tried every combination of minimatch, literals, wildcards, trailing slashes, whatever. Always triggers on every change.

**Comment by SebastianSchuetze** [comment]
@oising the support engineer already said that he could reproduce it. Let's wait.
Why are you sure they would say it is not reproducible?

**Comment by oising** [comment]
> @oising the support engineer already said that he could reproduce it. Let's wait.
> Why are you sure they would say it is not reproducible?

Because I've seen it brought up half a dozen times on both the Microsoft technical forums and uservoice and all times the MSFT rep couldn't repro, and other non-MSFT people would reply also to say it "works fine" -- it's a total heisenbug for most of us.

**Comment by SebastianSchuetze** [comment]
closing my PR, since I cannot find a solution yet.

**Pull request closed without merging**
