### PR TITLE
Add Get-VSTeamGroup / Get-VSTeamDescriptor

### PR DESCRIPTION
**Pull request by MichelZ**
# PR Summary

Add Get-VSTeamGroup / Get-VSTeamDescriptor

I'm looking to get this PR through before I add more commands related to this (e.g. New-VSTeamGroup ;) , Add-VSTeamGroupMember, Set-VSTeamAccessControlEntry, things like that), but I'd like to see if my contribution is up to the standards first.

Also, I seem to have (at least?) 1 failing Test, which I somehow cannot figure out... A little hint would be appreciated 🥇 

Executing script C:\MIZE\DEV\GitHub\vsteam\unit\test\groups.Tests.ps1

  `  Describing Groups VSTS
    Context Get-VSTeamGroup by project
      [-] Should return groups 122ms
        Expected Invoke-RestMethod in module VSTeam to be called 1 times exactly but was called 0 times
        34:             Assert-MockCalled Invoke-RestMethod -Exactly 1 -ParameterFilter {
        at <ScriptBlock>, C:\MIZE\DEV\GitHub\vsteam\unit\test\groups.Tests.ps1: line 34`

The Url looks exactly the same when I execute with -Verbose in a normal PS window... :(

Thanks!

## PR Checklist

- [X] [Write Help](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#write-help)
- [X] [Write Unit Test](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#write-unit-test)
- [X] [Update VSTeam.psd1](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#add-a-format-file)
- [X] [Update CHANGELOG.md](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#add-a-format-file)

### CODE REVIEW

**Comment by MichelZ** [comment]
Also, the other Unit Tests seem to work on my system, and I can't figure out what I'm doing wrong. I'm sure you can take a quick look and spot it immediately.. thanks! 👍

**Comment by DarqueWarrior** [comment]
I will review today.

**Comment by DarqueWarrior** [comment]
All the tests are passing now. Take a look at the changes I made to make sure they are in line with what you were going for. I would like to get all the commented out code either removed for working before we merge to master.

**Comment by MichelZ** [comment]
Thanks! Yes, the changes make sense, and I understand it now, perfect.
I'll give it another try to filter by SubjectTypes, or remove the code if I can't get it to work. Thanks for the help!

**Comment by MichelZ** [comment]
Found out how to use SubjectTypes, pushed changes with Docs and new Unit Tests.

**Comment by MichelZ** [comment]
@DarqueWarrior 
Are you waiting on anything from me to continue this merge?

**Comment by DarqueWarrior** [comment]
Sorry for the delay I am on a work trip. I am looking into now.

**Pull request merged**
