### PR TITLE
Added ability to pass parameters when queueing builds

### PR DESCRIPTION
**Pull request by karpis**
Also fixed some failing tests that were using removed parameters and obsolete Pester functions

### CODE REVIEW

**Comment by karpis** [comment]
Found an issue. Will fix and create a new PR

**Comment by karpis** [comment]
Found the problem. The parameters section of the request body is a string and must be serialized as such.

**Comment by DarqueWarrior** [comment]
Can you resolve the conflicts caused by the merge of your other PR?

**Comment by karpis** [comment]
Done :)

**Pull request merged**
