### PR TITLE
add membership functions

### PR DESCRIPTION
**Pull request by Seekatar**
# PR Summary

Added functions to add/delete/get Memberships.  I didn't add a type or format in this PR since memberships are just two ids.  I'd like to do another PR to add a Permissions container to the PSDrive with Group and User child items.

## PR Checklist

- [x] [Write Help](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#write-help)
- [x] [Write Unit Test](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#write-unit-test)
- [x] [Update VSTeam.psd1](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#add-a-format-file)
- [x] [Update CHANGELOG.md](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#add-a-format-file)

### CODE REVIEW

**Comment by Seekatar** [comment]
I see the build failed in the UT, but I can't reproduce locally on PS 5,6, or 7.  All succeed for me.

**Comment by DarqueWarrior** [comment]
reviewing now. Sometimes it fails due to the lack of permissions of PR builds.

**Comment by DarqueWarrior** [comment]
Can you clear this warning? 
##[warning]dist\vsteam.functions.ps1(5507,10): Warning : Function 'Remove-VSTeamMembership' has verb that could change system state. Therefore, the function has to support 'ShouldProcess'.

**Comment by Seekatar** [comment]
Warning fixed. 
Btw, I work with Jeffery at Clear-Measure and I've been using VSTeam for automating AzDo for a while.  I added some extensions, and am finally getting around to making some PRs.  Great lib!

**Comment by Seekatar** [comment]
I think the UT error is the cached call to project.  I added code I saw from other tests to avoid calling it.

**Comment by DarqueWarrior** [comment]
Sorry for delay. I will try to get to this this week.

**Pull request merged**
