### PR TITLE
Update Get-VSTeamRelease cmldet to get release via artifact ids

### PR DESCRIPTION
**Pull request by hkarthik7**
# PR Summary

Summary is in the comment below.

## PR Checklist

- [x] [Write Help](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#write-help)
- [x] [Write Unit Test](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#write-unit-test)
- [x] [Update CHANGELOG.md](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#update-changelogmd)

### CODE REVIEW

**Comment by hkarthik7** [comment]
Hi ya @SebastianSchuetze, @DarqueWarrior

I have added a new parameter 'artifactVersionId' to the function 'Get-VSTeamRelease'. I found this helpful as we can retrieve the associated release for a build using buildId(or artifactVersionId). I encountered a scenario where I had to fetch the list of pull requests and get it's associated build and releases, I was able to get the list of builds associated to a pull request but not the direct release associated to that build. Hence tried to achieve this by adding artifactVersionId to the function 'Get-VSTeamRelease'. 

This is working in my local dev environment and I'm using Windows 2016 Datacenter.

Apologies for failing the checks.

**Review by SebastianSchuetze — CHANGES_REQUESTED** [review]
When you can get the unit tests running on the agents then it would be fine. On first sight I can't see why they are not going through.

**Comment by hkarthik7** [comment]
@SebastianSchuetze there seems to be an issue only in the new test added, I tried to debug it locally and couldn't get through. Would you mind taking a look for me please?

Here is the modified version, I haven't pushed it to the repository yet as I'm afraid it may fail too.

```powershell
It 'with build Id should return release as Object' {
         ## Act
         Get-VSTeamRelease -ProjectName VSTeamRelease -artifactVersionId 101

         ## Assert
         Should -Invoke Invoke-RestMethod -Exactly -Scope It -Times 1 -ParameterFilter {
            $Uri -eq "https://vsrm.dev.azure.com/test/VSTeamRelease/_apis/release/releases?api-version=$(_getApiVersion Release)&artifactVersionId=101"
         }
}

**Comment by SebastianSchuetze** [comment]
@hkarthik7 it doesn't matter if it fails or the number commits you to have to do. This is why we have the build. And for the number of commits and the history, we do a squash merge anyways.

**Review by hkarthik7 — COMMENTED** [review]
Hi @SebastianSchuetze, I have updated the changes. Thank you.

**Comment by DarqueWarrior** [comment]
Why was this closed? Did I miss something?

**Comment by hkarthik7** [comment]
Hi ya, sorry about that I closed it by mistake.

**Review by SebastianSchuetze — APPROVED** [review]
looks good

**Pull request merged**
