### PR TITLE
Support for Task Groups

### PR DESCRIPTION
**Pull request by quintessential5**
# PR Summary

- support for task groups
- a typo fix
- ~a minor tweak to [my last accepted PR](https://github.com/DarqueWarrior/vsteam/pull/191): I didn't _applyTypesToVarGroup on the object returned~
- There are other changes that you made in [my last task group PR](https://github.com/DarqueWarrior/vsteam/pull/199) that you'll want to apply here.  I don't know how to get at them.

## PR Checklist

- [x] [Write Help](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#write-help)
- [x] [Write Unit Test](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#write-unit-test)

### CODE REVIEW

**Comment by quintessential5** [comment]
Will fix unit tests and re-submit.

**Comment by SebastianSchuetze** [comment]
@quintessential5 you don't have to close the pull request. Just work on that branch and commit again until all the code is as it should be. A PR does not have to include 100% working code. You can also open it as a draft.

**Comment by quintessential5** [comment]
> @quintessential5 you don't have to close the pull request. Just work on that branch and commit again until all the code is as it should be. A PR does not have to include 100% working code. You can also open it as a draft.

@SebastianSchuetze thanks for taking the time to communicate that.  I was planning on re-opening the PR as soon as I committed fixes to the breaking unit tests.  (I was also embarrassed to have even made a commit with broken tests; I thought I had verified that the tests were successful.)

**Comment by quintessential5** [comment]
Testing to see if re-opening the PR allows the latest commit to automatically show up and for the automated validation to be re-run...

**Comment by quintessential5** [comment]
Reverting a couple commits, in order to put them into a different PR, since I'm trying to make this the "task group support" PR.

**Comment by DarqueWarrior** [comment]
Can you make sure I have permissions to commit to this repo. There are changes I have to push before I this can be merged.

**Comment by quintessential5** [comment]
> Can you make sure I have permissions to commit to this repo. There are changes I have to push before I this can be merged.

@DarqueWarrior confirmed: "Allow edits from maintainers" is checked.

**Comment by DarqueWarrior** [comment]
> > Can you make sure I have permissions to commit to this repo. There are changes I have to push before I this can be merged.
> 
> @DarqueWarrior confirmed: "Allow edits from maintainers" is checked.

Not sure what is going on. Will keep looking.

```
remote: Permission to ucsb/ucsb-sa-enterprise-vsteam.git denied to DarqueWarrior.
fatal: unable to access 'https://github.com/ucsb/ucsb-sa-enterprise-vsteam.git/': The requested URL returned error: 403
```

**Comment by quintessential5** [comment]
> > > Can you make sure I have permissions to commit to this repo. There are changes I have to push before I this can be merged.
> > 
> > 
> > @DarqueWarrior confirmed: "Allow edits from maintainers" is checked.
> 
> Not sure what is going on. Will keep looking.
> 
> ```
> remote: Permission to ucsb/ucsb-sa-enterprise-vsteam.git denied to DarqueWarrior.
> fatal: unable to access 'https://github.com/ucsb/ucsb-sa-enterprise-vsteam.git/': The requested URL returned error: 403
> ```

I wonder if it's due to the fact that it's a UCSB repo; I wonder if there are some parent organizational settings that aren't allowing it to work.

On the other hand, it seems we had the same problem with the last pull request of mine, even when I used my personal repo?

**Comment by DarqueWarrior** [comment]
I am going to merge to a local branch and push from there to my repo. I don't want to loose time trying to figure this out.

**Comment by quintessential5** [comment]
> I am going to merge to a local branch and push from there to my repo. I don't want to loose time trying to figure this out.

I was able to add you as a collaborator to the repo, so maybe it'll work now (it was done around 9:15 or 9:30 Pacific).  However, of course, whatever's easiest for you.

**Comment by DarqueWarrior** [comment]
Changes merged into PR #217

**Pull request closed without merging**
