### PR TITLE
Added CMDLET to delete workitem

### PR DESCRIPTION
**Pull request by SebastianSchuetze**
# PR Summary

I added a new cmdlet to delete work items by IDs. I

So the following things were added:
* cmdlet Remove-VSTeamWiql
   * added also the switch parameter "Destroy" to also permanently delete the work item instead on putting it to the recycle bin
* added a format file for the cmdelet
* added a type file for the cmdlet

## PR Checklist

- [X] [Write Help](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#write-help)
- [X] [Write Unit Test](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#write-unit-test)
- [X] [Update VSTeam.psd1](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#add-a-format-file)
- [X] [Update CHANGELOG.md](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#add-a-format-file)

### CODE REVIEW

**Comment by SebastianSchuetze** [comment]
@DarqueWarrior I accidentally merged the other topic branch into this one in the beginning. So it shows the history of the not yet merged PR and also the comments above. I don't know if that will be a problem.

**Comment by DarqueWarrior** [comment]
Make sure you run

```PowerShell
.\Build-Module.ps1 -analyzeScript -ipmo
```
And clear any messages. 

I am a big unclear why we need _applyTypesToWorkItemDeleted and can't use _applyTypesToWorkItem

**Comment by DarqueWarrior** [comment]
I will take care of these changes.

**Comment by SebastianSchuetze** [comment]
Just for the explanation. I created _applyTypesToWorkItemDeleted because the return JSON object is not consistent with a normal work item object. Strange enough, even the property names are different.
for example, the name of the work item when you query it is "title". But the object returned from the API when you delete it has the property named "name" and not "title"

This is for several properties. So I thought a new method is needed because I also created a new format.

Unless you tell me, that this can be done differently, then I am happy to know how it can be done simpler.

**Comment by DarqueWarrior** [comment]
Can you think of a scenario where you are going to save the returned deleted item? In all the rest of the remove calls we don't return the object. I think to stay consistent I will just not return anything here either.  I am almost done with all the changes. There is nothing for you to do at this point.

**Comment by DarqueWarrior** [comment]
Changes merged into PR #217

**Pull request closed without merging**
