### PR TITLE
fix typo in intergration test parameters

### PR DESCRIPTION
**Pull request by CodedBeard**
fix integration test issue with #51 due to missing -endpointName parameter

### CODE REVIEW

**Comment by DarqueWarrior** [comment]
I just realized another reason I am having issues. This appears to only be supported on TFS 2018 and VSTS.  VSTeam also supports TFS 2017.  We need to post an error to the user when they attempt to do this on a TFS 2017 connection. There is an example of this on the in users. _supportsMemberEntitlementManagement

**Comment by CodedBeard** [comment]
Ah sorry, thought it was in 2017 and forgot to double check. Have sent the pr with the required changes, based off of users. _supportsMemberEntitlementManagement as you suggested.

**Comment by DarqueWarrior** [comment]
No problem. I happen to have a TFS 2017 and 2018 setup just for this purpose. Thanks for the quick turn around and support.

**Comment by CodedBeard** [comment]
Your welcome, Let me know if it needs any more tweaks.
Thanks for making the project in the first place, you've saved me so much time with vsteam migrating all our old projects to containers 👍

**Pull request merged**
