### PR TITLE
Add functions to get/edit code policies

### PR DESCRIPTION
**Pull request by davidroberts63**
Adds functions for getting and editing code policies such as 'Minimum number of reviewers'.

### CODE REVIEW

**Comment by davidroberts63** [comment]
And of course I realize I didn't update the readme. I'll get that in the next day.

**Comment by DarqueWarrior** [comment]
Funny I am updating the Readme now myself.  Broke my own rules.

**Comment by davidroberts63** [comment]
Also note, I did put int he docs but I was unable to successfully run the gen-help.ps1. Looks like there are a number of dependencies to get that to work, node, some npm modules etc. I'm not familiar with some of the other tools (node and npm yes but the specific modules no). I'd be willing to work on adding some documentation of getting started with the gen-help script in a separate PR if you want. I'd just need a bit more info on what you do on your side to get gen-help to run correctly.

**Comment by DarqueWarrior** [comment]
I just updated the help for you and some other files.

**Comment by davidroberts63** [comment]
Wonderful. Thanks! Do you happen to know of any good articles on generating those formats and ps type files? It looks like they are generated by something (from the comment header) but everything I read is making them by hand. So I just copied an existing one.

**Comment by DarqueWarrior** [comment]
I started from one provided by PowerShell. Everything I found said to copy one from PowerShell and modify.  So that is what I do as well.

Sorry for the delay. I had some meetings but I have started reviewing again. Looks really good. Thanks for the PR.

**Comment by davidroberts63** [comment]
No problem. Thanks for making this and for taking the time from the LoECDA.

P.S.
Tell Damian I said hello.

**Comment by davidroberts63** [comment]
Is there anything else I can do to help on this PR? I know your busy so just checking in.

**Comment by DarqueWarrior** [comment]
Can you explain to me how the second catch will ever get a WebException? I left a comment on the code.

**Comment by davidroberts63** [comment]
Those operations (Add,Update,Delete) can result in the server returning an error (400, 404, etc). Truth be told I simply copied from similar existing operations for the git repositories functions so I could try to be somewhat consistent. I could modify it to be similar to another area if there is a preference.

Didn't see a comment anywhere (in this PR or the code itself) so I hope I addressed your thoughts. Thank you for taking the time on reviewing this.

**Comment by DarqueWarrior** [comment]
Thanks for pointing that out. I will approve the PR and go find the other code like this a refactor it all.

**Pull request merged**
