### PR TITLE
Improve integration test with user cleanup

### PR DESCRIPTION
**Pull request by MichelZ**
# PR Summary

Improve integration test with user cleanup

## PR Checklist

- [ ] [Write Help](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#write-help)
- [ ] [Write Unit Test](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#write-unit-test)
- [ ] [Update CHANGELOG.md](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#add-a-format-file)
(not needed)

### CODE REVIEW

**Comment by SebastianSchuetze** [comment]
can you update your PR I merged #259 and run the build again?

**Comment by MichelZ** [comment]
@SebastianSchuetze Done

**Comment by DarqueWarrior** [comment]
Was merged but did not auto close.

**Comment by DarqueWarrior** [comment]
Might have to roll this back.

Describing VSTeam Integration Tests
    [-] Error occurred in Describe block 236ms
      ParameterBindingException: A parameter cannot be found that matches parameter name 'Email'.
      at <ScriptBlock>, /Users/runner/runners/2.165.0/work/1/Test/integration/test/010_projects.Tests.ps1: line 65
      at Invoke-Blocks, /Users/runner/.local/share/powershell/Modules/Pester/4.3.1/Functions/SetupTeardown.ps1: line 140
      at Invoke-TestGroupTeardownBlocks, /Users/runner/.local/share/powershell/Modules/Pester/4.3.1/Functions/SetupTeardown.ps1: line 130
      at DescribeImpl, /Users/runner/.local/share/powershell/Modules/Pester/4.3.1/Functions/Describe.ps1: line 166

**Comment by MichelZ** [comment]
@DarqueWarrior I've seen it, yes. Will fix that tomorrow. Any way I can start integration tests myself?

**Comment by DarqueWarrior** [comment]
Yes they are just pester tests. The environment vars that are needed to be set are described at the top of the file. I will also update the contribution file to explain how to run them. But you must be very careful. They are **destructive**! You need to have a test org to use. **_Everything in them will be deleted!_**

**Pull request closed without merging**
