### PR TITLE
Added breaking change warning and new version notification on module load

### PR DESCRIPTION
**Pull request by SebastianSchuetze**
Added notification message if a new version is abailable.

Added warning message for upcoming changes in #438

### CODE REVIEW

**Comment by SebastianSchuetze** [comment]
@DarqueWarrior what do you think of this?

I found a way that is cheaper than checking PS Gallery. We go directly to GitHub and that is fast enough to check on every module load:

image

**Comment by SebastianSchuetze** [comment]
Also do you think the warning message is enough or should I not add this hard coded?

**Comment by SebastianSchuetze** [comment]
I just need to find a way that this is not called during unit tests. Seems to stress the rate limit of the GitHub API too much. 😆

**Comment by DarqueWarrior** [comment]
Have you tried putting this in the psm1 file instead of calling it on every web request that should only be run when the module is loaded.

**Comment by SebastianSchuetze** [comment]
It is in the psm1 file 🙂. But unit tests seem to load the whole module several times.

But I got an idea. Maybe I offer an option with an environment variable that is checked with boolean.

So people can turn of the warning. And also the update notification.

**Pull request merged**
