### PR TITLE
Added basic support for any work item field for work item cmdlets

### PR DESCRIPTION
**Pull request by SebastianSchuetze**
# PS Summary

Added the possibility to set any work item fields with Add-VSTeamWorkItem and Update-VSTeamWorkItem. This is solved by using a hash table parameter and adding them dynamically to the JSON body.

## PR Checklist

* [X] Write Help
* [X] Write Unit Test
* [X] Update VSTeam.psd1
* [X] Update CHANGELOG.md

### CODE REVIEW

**Comment by SebastianSchuetze** [comment]
related to #188

**Comment by DarqueWarrior** [comment]
Can you update the help to explain what will happen if they add description to the hashtable? I would like that in the help instead of the user having to hit the error to find out.

**Comment by SebastianSchuetze** [comment]
Yes, I will do that ASAP.

**Comment by SebastianSchuetze** [comment]
Added the comments in the "Notes" section. Tell me if that is the appropriate place or if that should be written directly attached to the parameter description.

**Comment by SebastianSchuetze** [comment]
@DarqueWarrior is the documentation you requested fine for you?

**Pull request merged**
