### PR TITLE
Fix Update-VSTeamUserEntitlement to correctly use contentype application/json-patch+json

### LINKED ISSUE #417: Update-VSTeamUserEntitlement not working to update user acesslevel
I am trying to update user accesslevel using below command and throws up an error. 

Update-VSTeamUserEntitlement -Email xxxxxxxx@gmail.com -License express

Confirm
Are you sure you want to perform this action?
Performing the operation "Update user" on target "xxxxxxxxxx (xxxxxxxx@gmail.com)".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): y
WARNING: The request indicated a Content-Type of "application/json-patch+" for method type "PATCH" which is not supported. Valid content types for this method are:
application/json-patch+json.
Invoke-RestMethod : {"$id":"1","innerException":null,"message":"The request indicated a Content-Type of \"application/json-patch+\" for method type \"PATCH\" which is not supported. Valid
content types for this method are: application/json-patch+json.","typeName":"Microsoft.VisualStudio.Services.WebApi.VssRequestContentTypeNotSupportedException,
Microsoft.VisualStudio.Services.WebApi","typeKey":"VssRequestContentTypeNotSupportedException","errorCode":0,"eventId":3000}
At C:\Program Files\WindowsPowerShell\Modules\VSTeam\7.4.0\vsteam.functions.ps1:266 char:18
+          $resp = Invoke-RestMethod @params
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Steps to reproduce
------------------

```powershell

```

Expected behavior
-----------------

```none

```

Actual behavior
---------------

```none

```

Environment data
----------------

OS

- [ ] macOS
- [ ] Windows
- [ ] Linux

Server

- [ ] Azure DevOps Service

```powershell
> Get-VSTeamAPIVersion
PS C:\windows\system32> Get-VSTeamAPIVersion


Billing                     : 5.1-preview.1
Build                       : 5.1
Core                        : 5.1
DistributedTask             : 6.0-preview
DistributedTaskReleased     : 5.1
ExtensionsManagement        : 6.0-preview
Git                         : 5.1
Graph                       : 6.0-preview
HierarchyQuery              : 5.1-preview
MemberEntitlementManagement : 6.0-preview
Packaging                   : 6.0-preview
Pipelines                   : 5.1-preview
Policy                      : 5.1
Processes                   : 6.0-preview
Release                     : 5.1
ServiceEndpoints            : 5.0-preview
TaskGroups                  : 6.0-preview
Tfvc                        : 5.1
VariableGroups              : 5.1-preview.1
Version                     : VSTS
```

```powershell
> $PSVersionTable

PS C:\windows\system32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.1237
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1237
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

### PR DESCRIPTION
**Pull request by thahif**
# PR Summary

## PR Checklist

- [ ] [Write Help](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#write-help)
- [ ] [Write Unit Test](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#write-unit-test)
- [ ] [Update CHANGELOG.md](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#update-changelogmd)

### CODE REVIEW

**Comment by thahif** [comment]
@SebastianSchuetze  - PR raised. Can you take it fwd from here?

**Comment by SebastianSchuetze** [comment]
@thahif could you check that you allowed me to make updates in your branch as a maintainer?

Otherwise you would need to update the changelog.md in the same way like the other entries. Your change would fit in version 7.5.0

image

**Comment by thahif** [comment]
@SebastianSchuetze  -  I see that you can edit my branch. 

image

**Comment by SebastianSchuetze** [comment]
Strange. I can't edit the branch.

**Comment by thahif** [comment]
@SebastianSchuetze - what do we next? I have re-applied that allow edit by maintainers permission. Can you please check?

**Comment by SebastianSchuetze** [comment]
If not then I will use your branch in one of mine and merge that one. This I would close then.

**Comment by thahif** [comment]
@SebastianSchuetze  - Any timeline that you can comment when this will be available to download?

**Comment by SebastianSchuetze** [comment]
I will try my best but first I need to solve this #424 and it is usually happening outside of my worktime. So no ETA I can only try to give my best. Even if I merge it it will not be available before release works.

**Comment by SebastianSchuetze** [comment]
But you might want to check the cmdlet Invoke-VSTeamRequest which allows you to address any API of AzDO with your own custom JSON body. In that way you might have a work around in the mean time.

You just need to handle the API yourself a bit. Or even copy the code and reuse it with this command.

**Comment by SebastianSchuetze** [comment]
I solved finally the problem with the workflow.... or at least nearly. I will be working on your PR and merge it as soon as possible.

**Review by SebastianSchuetze — APPROVED** [review]

**Pull request merged**
