### PR TITLE
bug fix for update and add workitem

### PR DESCRIPTION
**Pull request by SebastianSchuetze**
Is connected to the issue #196 which fixes the described problem

### CODE REVIEW

**Comment by SebastianSchuetze** [comment]
@DarqueWarrior the build fails for the unit tests. The error is so strange to me, that I don't know what the problem is:
https://loecda.visualstudio.com/Team%20Module/_build/results?buildId=1636&view=logs&j=39439fd4-3ef0-56a3-10f8-5cf61d2586e7&t=86c182c9-17cb-535d-0483-c36562050943&l=1618

I know what it says, but with the unit tests provided it should not be a problem. In theory, they should be correct! Do you have any idea?

**Comment by DarqueWarrior** [comment]
I will find time to review today.

**Comment by DarqueWarrior** [comment]
I get the same errors when I run the test locally as well. Are they passing for you on your machine?

**Comment by DarqueWarrior** [comment]
The tests are failing correctly. In the Assert-MockCalled you are testing for 
```
$Body -like '*Testing*' -and
```

The body does not contain **Testing** so that Assert will fail. On line 28 un-comment out that line so it will show you the REST Call and you can see what you can and can't test for. 

Just make sure and comment it out again before submit.

**Comment by DarqueWarrior** [comment]
You would have to assert each part of the request separate and fail just that part. The quick way around this is to uncomment the line in the mock until the test is working.

**Comment by SebastianSchuetze** [comment]
@DarqueWarrior unit tests pass now, but the Package Management Stage seems to fail.
Btw. how does it work with GitHub? Shouldn't only the build stages be tested on the Azure Pipelines instead of the whole pipeline?

**Comment by DarqueWarrior** [comment]
Yeah I need to only have the build run. The release is not going to work for permission reasons. I will work to fix that.

**Comment by DarqueWarrior** [comment]
Please make sure I permission to push to this PR.

**Comment by DarqueWarrior** [comment]
Not sure why I was getting an error? hmm.

**Comment by DarqueWarrior** [comment]
remote: Permission to RazorSPoint/vsteam.git denied to DarqueWarrior.
fatal: unable to access 'https://github.com/RazorSPoint/vsteam.git/': The requested URL returned error: 403

**Comment by SebastianSchuetze** [comment]
What changed? Where there some permission errors?

**Pull request merged**
