### PR TITLE
Added tag and relationship link functionality to updating work items

### PR DESCRIPTION
**Pull request by jarlbrak**
# PR Summary

## PR Checklist

- [x] [Write Help](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#write-help)
- [ ] [Write Unit Test](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#write-unit-test)
- [ ] [Update VSTeam.psd1](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#add-a-format-file)
- [ ] [Update CHANGELOG.md](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#add-a-format-file)

### CODE REVIEW

**Comment by jarlbrak** [comment]
@DarqueWarrior I would appreciate some help with the YAML error here. Thanks!

**Comment by DarqueWarrior** [comment]
What are you trying to do with the lines below?  
```
Properties: [string] rel - relationship type
            [string] url - url to the work item to be linked
            [string] comment - comment on why the link is being made
```
There is a format for the md help files and these lines violate it.

**Comment by DarqueWarrior** [comment]
I just pushed changes I think fix the issue for you.

**Comment by jarlbrak** [comment]
Thank you for the help!ww

**Comment by DarqueWarrior** [comment]
Are you ready for this to be merged now?

**Comment by DarqueWarrior** [comment]
Looks like the Add-VSTeamWorkItem.md was not updated. And Update-VSTeamWorkItem.md does not have CustomFields explained.

**Comment by jarlbrak** [comment]
I will fix and make a new PR when I'm ready.

**Pull request closed without merging**
