### PR TITLE
Add Update-VSTeamPullRequest and Add-VSTeamPullRequest

### LINKED ISSUE #120: Feature request: Ability to set Pull Request status
I am interested in having a command that will allow me to set the status of an active pull request. By "status", I am referring to the drop down options Complete, Set auto-complete, Mark as draft, and Abandon (Figure 1).

**Figure 1**

image

### LINKED ISSUE #131: [Feature] Add `New-VSTeamPullRequest` command
Currently there is no `New-VSTeamPullRequest` function 

This would be a great addition and would enable more complex automated end to end, branch to branch feature development practices like

PR into Dev Branch -> build completes -> PR is merged -> Merged Branch Builds -> Release runs -> New PR to Test Branch -> PR Completes -> Test Branch Builds -> Test Release Runs > New PR to Prod Branch -> PR Completes -> Prod Branch Builds -> Prod Release Runs 

This allows a totally segregated & isolated model between Builds/Releases and the differing stages at which these run at although does add extra complexity

### PR DESCRIPTION
**Pull request by MichelZ**
# PR Summary

Add Update-VSTeamPullRequest
Add Add-VSTeamPullRequest
Fixes #120 
Fixes #131 

## PR Checklist

- [x] [Write Help](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#write-help)
- [x] [Write Unit Test](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#write-unit-test)
- [x] [Update CHANGELOG.md](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#add-a-format-file)

### CODE REVIEW

**Comment by SebastianSchuetze** [comment]
thx, gonna review this soon

**Comment by MichelZ** [comment]
I think CI builds fail not because of the changes here, but because of flawed tests.
Fixed in #242

**Comment by DarqueWarrior** [comment]
OK I have a few questions on this one. In Update-VSTeamPullRequest:
Why do we need both -Draft and -Publish?  It appears that -Draft should be enough. If it is present you set the body to true if not to false. Why do I need them both?

Also the ProjectName parameter is never used and seems like it can be removed from Update-VSTeamPullRequest.

**Comment by DarqueWarrior** [comment]
I will make the changes I think need to be made and commit them so we can review.

**Comment by DarqueWarrior** [comment]
Hey @MichelZ  and @SebastianSchuetze  can you look at my changes and make sure I have not missed anything.

**Comment by MichelZ** [comment]
@DarqueWarrior @SebastianSchuetze The reason that both are there: It's more explicit. e.g. if you update a draft to published, now you have to:
`Update-VSTeamPullRequest -PullRequestId 1234`
That doesn't seem descriptive or intuitive, where:
`Update-VSTeamPullRequest -PullRequestId 1234 -Publish`
feels very logical.

Also, if you want to e.g. update a draft pull request with anything, you have to think about including `-Draft` that it stays draft, else it gets automatically published. That screams "bug" to me :)

**Pull request merged**
