### PR TITLE
Added cmdlets for add, get and remove for classification nodes, iterations and areas

### PR DESCRIPTION
**Pull request by SebastianSchuetze**
# PR Summary

Adding the follwoing cmdlet 

* Add-VSTeamClassificationNode
* Add-VSTeamIteration
* Add-VSTeamArea
* Get-VSTeamIteration
* Get-VSTeamArea
* Remove-VSTeamArea
* Remove-VSTeamIteration
* Remove-VSTeamClassificationNode

the last for only use the more basic functions using the ClassificationNode. But inproves usability and are basically just a wrapper.

## PR Checklist

- [x] [Write Help](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#write-help)
- [x] [Write Unit Test](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#write-unit-test)
- [ ] [Update CHANGELOG.md](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#update-changelogmd)

### CODE REVIEW

**Comment by DarqueWarrior** [comment]
I assume this is a work in progress? I only see one file changed.

**Comment by SebastianSchuetze** [comment]
Yes it is WIP.

**Comment by SebastianSchuetze** [comment]
#276 is related

**Comment by DarqueWarrior** [comment]
You want me to help you convert these functions to use the attributes?

**Comment by SebastianSchuetze** [comment]
@DarqueWarrior yes, please. I guess you talk about the changes you made?

**Comment by SebastianSchuetze** [comment]
Finally got the unit tests running. Also added Get-VSTeamIteration and Get-VSTeamArea. Now we have Add, Get and Remove cmdlets completed with unit tests.

Also adjusted to the new project attribute. I saw that there is still 3-4 cmdlet who use the old approach. I will handle it in another PR.

**Pull request merged**
