### PR TITLE
Added CMDLET to get work items via WIQL

### PR DESCRIPTION
**Pull request by SebastianSchuetze**
# PR Summary

I added a new cmdlet which was suggested with the issue #175. I had asked some questions regarding some more changes that needed to be made. Since I didn't get an answer yet, I just went with my idea anyways.

So the following things were added:
* cmdlet Get-VSTeamWiql
   * added an extra parameter "Expand" to the cmdlet to already load all the work items with the given columns in the WIQL command. By default only URL and work item IDs are given
* added -Team parameter to buildRequestURI and _callAPI because it was not supported by them to have this covered.
* added a format file for the cmdelet
* added a type file for the cmdlet

## PR Checklist

- [X] [Write Help](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#write-help)
- [X] [Write Unit Test](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#write-unit-test)
- [x] [Update VSTeam.psd1](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#add-a-format-file)
- [x] [Update CHANGELOG.md](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#add-a-format-file)

### CODE REVIEW

**Comment by SebastianSchuetze** [comment]
@DarqueWarrior if my approach with the private functions were correct. Where should I unit test them, if you have some already?

**Comment by DarqueWarrior** [comment]
Sorry for delay. I am recovering from surgery. I will get to this ASAP.

**Comment by SebastianSchuetze** [comment]
NP! Take your time!

**Comment by DarqueWarrior** [comment]
Can you sync your repo? Your Build-Module.ps1 is old. The new version runs tests and static code analysis .

**Comment by SebastianSchuetze** [comment]
@ferwe I gonna improve that. Thanks!

**Comment by SebastianSchuetze** [comment]
@DarqueWarrior I merged the newest version and also updated the psd and changelog

**Comment by DarqueWarrior** [comment]
Just got a break at Ignite. Going to process as many as I can today.

**Pull request merged**
